### ISSUE TITLE
Missing tag for 1.5.0 release

### ISSUE THREAD

**Issue by define-null** [for-GET/jesse#56]
I noticed that although 1.5.0 release is mentioned almost in the changelog a year ago the corresponding tag is missing

**Comment by andreineculau** [comment]
That's true. The reason though is that 1.5.0 is "upcoming". I didn't want to tag it at that point, because I wanted people to test and come with feedback since I couldn't test in depth. Meanwhile, there was good feedback, but I became short of time plus there's a couple of interesting PRs, so you could say I forgot to "release".

I pushed two tags `1.5.0-rc1` and `1.5.0-rc2` tag that you can use for now.
Feel free to keep the issue open and I'll close when I release 1.5.0 :)

**Comment by define-null** [comment]
Great, thank you)

**Comment by mrallen1** [comment]
Hey @Licenser can you maybe upload a new hex release with one of these rc tags?

**Comment by Licenser** [comment]
I can but there is a slight problem. I think to remember that hex/rebar3 had serious problems with `-rc` tags (aka it didn't take them properly into account and would make sorting / finding the 'latest' package problematic. Releasing it as 1.4.1 also seems wrong not 100% sure about how to handle this best.

**Comment by andreineculau** [comment]
published https://github.com/for-GET/jesse/releases/tag/1.5.0

**Comment by mrallen1** [comment]
@Licenser Can you put this release on hex pretty please? There's :cake:

**Comment by mrallen1** [comment]
bump for @Licenser :)
