### ISSUE TITLE
Greatly expand the documentation around how $ref works

### ISSUE THREAD

**Issue by mrallen1** [for-GET/jesse#57]
It is really really really really really super opaque, frustrating and annoying to figure out how `$ref` is supposed to work.

I think I'm too close to my emotions to write clearly and calmly about this, but I [started a gist][1] with some of my research notes.  I'd eventually like to incorporate those notes in a cleaned up form into the documentation or README.

Is there an appetite to 👍 on a PR which simply attempts to see if the given `$ref` key matches any records in ETS before all the canonicalization happens?

[1]: https://gist.github.com/mrallen1/c49eaa48dbe8fc3f69ae44defbc287b3

**Comment by andreineculau** [comment]
@mrallen1 let me first say that a PR does not need approval, and it is most certainly a pleasure to go through any PR, no matter if it ends up in a merge, as long as there's added value. If you open an issue though, please specify which version of `jesse` you have a question on/problem with - 1.5.0-rc2 ? CLI or erlang interface ?

As to the point, `jesse` does not and should not do anything except follow the standards, if not fully, then at the very least a subset of the standards (and then clarify exactly which subset; similarly as we stated in the beginning that `jesse` adheres to json schema draft v3, but with no support for `$ref` at all, for example).

So to list down the relevant standards:
- `$ref` is described here http://json-schema.org/latest/json-schema-core.html#rfc.section.8
- a document is given a base URI based on http://json-schema.org/latest/json-schema-core.html#rfc.section.9.1 and https://tools.ietf.org/html/rfc3986#section-5 respectively
- `$id` is described here http://json-schema.org/latest/json-schema-core.html#id-keyword

My immediate questions would then be:
1. did you read through those docs?
2. is `jesse` failing to adhere to any of that?

---

Regarding your gist

> I spent well over 30 hours trying to figure it out

Sorry to hear that, but I would kindly suggest you to ping this or any other repo well before you hit those 30 hours. I myself would have replied much faster than I'm doing now - with at least the bare information to keep you away from all those nice words you have sprinkled your gist with.

> Apparently it is not possible to have "naked" references for reasons I can't possibly fathom

It is not about the references, as it is about the ids.

Although `id` was under-specified in `draft3` (you do not specify `$schema` and `jesse` will default to `draft3`), it still states that it is an `URI` https://tools.ietf.org/html/draft-zyp-json-schema-03#section-5.27 . In your gist, neither `record` nor `record-bulk` are URIs.

Ways to make your gist to work with no change to `jesse` 1.5.0-rc2:
1. `record-bulk.json` should reference `record.json` schema as `{"$ref": "./record.json"}` (i.e. by file path, instead of by id), in which case you can actually just remove the `id` in both
2. use proper URI ids

I have pushed a branch `non-uri-ids` that transforms non-URI ids into URI ids based on the source key (where the schema was loaded - which will surely be an URI). If you can take that version for a drive, I'd appreciate it.

**Comment by mrallen1** [comment]
OK, thanks for the explainer. Yes my language was intemperate and needs to be edited - it was the voice of frustration.  Thank you for understanding. I'll edit my gist and try out the branch probably tomorrow.

**Comment by andreineculau** [comment]
@mrallen1 any feedback to report? thanks

**Comment by andreineculau** [comment]
I went a bit ahead of the game and merged that branch. If you find smth erroneous, I'll reopen.

**Comment by mrallen1** [comment]
Thanks again. I have a new project I'm working on for $DAYJOB so I'll use it there for certain. Any chance you'd tag a new release? ^_^
